// Generated by CoffeeScript 1.6.2
(function() {
  var Capirona, Context;

  Context = require("./context");

  Capirona = (function() {
    function Capirona() {}

    /*
    */


    Capirona.prototype.run = function(source, context, callback) {};

    return Capirona;

  })();

  exports.run = function(source, context, callback) {
    return new Capirona().run(source, context, callback);
  };

  exports.Context = Context;

}).call(this);
